apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineList
items:
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: openstack-master-
    labels:
      set: master
      cluster.k8s.io/cluster-name: test1
  spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        flavor: m1.medium
        image: ubuntu
        keyName: cluster-api-provider-openstack
        availabilityZone: nova
        networks:
        - uuid: ff0f5226-f887-43e5-b2ee-d90974c444ea
        floatingIP: 5.5.5.199
        rootVolume:
          diskSize: 0
          sourceType: ""
          SourceUUID: ""
        securityGroups:
        - uuid: 5048bf14-feb0-4481-b485-68d54b023dd3
        userDataSecret:
          name: master-user-data
          namespace: openstack-provider-system
        trunk: false
        tags:
          - a-machine-specific-tag
        serverMetadata:
          key: value
    versions:
      kubelet: 1.15.0
      controlPlane: 1.15.0
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: openstack-node-
    labels:
      set: node
      cluster.k8s.io/cluster-name: test1
  spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        flavor: m1.medium
        image: ubuntu
        keyName: cluster-api-provider-openstack
        availabilityZone: nova
        networks:
        - uuid: ff0f5226-f887-43e5-b2ee-d90974c444ea
        floatingIP: 5.5.5.183
        securityGroups:
        - uuid: 5048bf14-feb0-4481-b485-68d54b023dd3
        userDataSecret:
          name: worker-user-data
          namespace: openstack-provider-system
        trunk: false
        tags:
          - a-machine-specific-tag
        serverMetadata:
          key: value
    versions:
      kubelet: 1.15.0
