apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: test1-machinedeployment
  labels:
    cluster.k8s.io/cluster-name: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.k8s.io/cluster-name: test1
      set: node
  template:
    metadata:
      labels:
        cluster.k8s.io/cluster-name: test1
        set: node
    spec:
      providerSpec:
        value:
          apiVersion: "openstackproviderconfig/v1alpha1"
          kind: "OpenstackProviderSpec"
          flavor: m1.medium
          image: ubuntu
          keyName: cluster-api-provider-openstack
          availabilityZone: nova
          networks:
          - uuid: ff0f5226-f887-43e5-b2ee-d90974c444ea
          securityGroups:
          - uuid: 5048bf14-feb0-4481-b485-68d54b023dd3
          userDataSecret:
            name: worker-user-data
            namespace: openstack-provider-system
          trunk: false
          tags:
          - a-machine-specific-tag
          serverMetadata:
            key: value
      versions:
        kubelet: 1.15.0
